.\" Process this file with
.\" groff -man -Tascii supybot-reset-password.1
.\"
.TH SUPYBOT-RESET-PASSWORD 1 "JUNE 2022"
.SH NAME
supybot-reset-password \- Changes a user's password in a Supybot users.conf file
.SH SYNOPSIS
.B supybot-reset-password
.RI [ options ] " users.conf
.SH DESCRIPTION
.B supybot-reset-password
changes a user's password in a Supybot users.conf file
.SH OPTIONS
.TP
.B \-\^\-version
Show version of program.
.TP
.BR \-h ", " \-\^\-help
Show summary of options.
.TP
.BR \-u " NAME" "\fR,\fP \-\^\-username=" NAME
Specifies the username to use for the new user.
.TP
.BR \-p " PASSWORD" "\fR,\fP \-\^\-password=" PASSWORD
Specifies the new password to use for the new user.
.SH "SEE ALSO"
.IR python (1),
.IR supybot (1),
.IR supybot-adduser (1)
.SH AUTHOR
This manual page was originally written by Valentin Lorentz
<progval plus limnoria at progval dot net>.  Permission is granted to copy,
distribute and/or modify this document under the terms of the Supybot
license, a BSD-style license.

