.\" Process this file with
.\" groff -man -Tascii supybot-newplugin.1
.\"
.TH SUPYBOT\-NEWPLUGIN 1 "SEPTEMBER 2004"
.SH NAME
supybot\-newplugin \- A wizard for creating Supybot plugins
.SH SYNOPSIS
.B supybot\-newplugin
.RI [ options ]
.SH DESCRIPTION
.B
supybot\-newplugin
is a wizard that creates a template python source file for a new
.IR supybot (1)
plugin.
.SH OPTIONS
.TP
.B \-\^\-version
Show version of program.
.TP
.BR \-h ", " \-\^\-help
Show summary of options.
.TP
.BR \-r ", " \-\^\-regexp
Uses a regexp\-based callback.
.TP
.BI \-n " NAME" "\fR,\fP \-\^\-name=" NAME
Sets the name for the plugin.
.TP
.BR \-t ", " \-\^\-thread
Makes the plugin threaded.
.SH "SEE ALSO"
.IR python (1),
.IR supybot (1),
.IR supybot\-wizard (1),
.IR supybot\-adduser (1),
.SH AUTHOR
This manual page was originally written by James Vega
<vega dot james at gmail dot com>.  Permission is granted to copy,
distribute and/or modify this document under the terms of the Supybot
license, a BSD\-style license.
